# Generated by Django 5.2.1 on 2025-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('major', models.CharField()),
                ('grade', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField()),
            ],
        ),
    ]
